"""added followers table

Revision ID: 15209f710bba
Revises: 50e0de21fe3a
Create Date: 2018-04-10 17:37:24.289429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15209f710bba'
down_revision = '50e0de21fe3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
