"""add language to messages

Revision ID: ded0a8ceeb69
Revises: 2558d4346c86
Create Date: 2018-05-06 22:36:29.177053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded0a8ceeb69'
down_revision = '2558d4346c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'language')
    # ### end Alembic commands ###
